# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/kinetics/val_data_boneA.npy
  label_path: ./data/kinetics/val_label.pkl
  debug: False

# model
model: model.aagcn.Model
model_args:
  num_class: 3
  num_person: 1
  num_point: 19
  graph: graph.kinetics_global.Graph
  graph_args:
    labeling_mode: 'spatial'


# test 
phase: val
device: 0
test_batch_size: 64
weights: ./pre_train/ki_agcn_boneA.pt


work_dir: ./work_dir/kinetics/agcn_boneA_val
model_saved_name: ./runs/ki_agcn_boneA_val_global
save_score: True